name: verify-functionality
on:
  workflow_dispatch:
  
jobs:
  couchdb3-clouseau:
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Fire up CouchDB
        uses: ottcsconsult/couchdb-github-action@master
        with:
          couchdb-version: latest

      - name: Test CouchDB
        run: |
          curl -f http://127.0.0.1:5984/
